### ISSUE TITLE
Create sub-domain intranet-api.bocacode.com to point to API firebase project/GC

### ISSUE THREAD

**Issue by cassichan** [bocacode/bocacode-intranet-api-typescript#7]
Firebase project: bocacode-intranet-api

**Comment by toddalbert** [comment]
@cassichan -- can you tell me the exact URL you want me to point `intranet-api.bocacode.com` to?

**Comment by cassichan** [comment]
@toddalbert  https://bocacode-intranet-api.uc.r.appspot.com
